#Define circleci version to run the pipeline 
version: 2.1 

orbs:
  node: circleci/node@4.1

#These are the different jobs that will be run in our pipeline 
jobs: 
  run_tests:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Run Unit Tests
          command: |
            ./node_modules/mocha/bin/mocha test/

  build_deploy_docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            export TAG=0.2.<< pipeline.number >>
            export IMAGE_NAME=$circle_project_name
            docker build -t $IMAGE_NAME . 
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $DOCKER_LOGIN/$IMAGE_NAME

      - run:
          name: deploy to app engine 
          command: |
            echo ${GCLOUD_KEY} > /tmp/sa_key.json
            gcloud auth activate-service-account --key-file/tmp/sa_key.json
            rm /tmp/sa_key.json 
            gcloud config set project applicationdeploy-316402
            gcloud config set compute/region us-east1
            gcloud app deploy
          

workflows:

  build-and-test:
    jobs:
    - run_tests
    - build_deploy_docker_image
      